require('base')
require('highlights')
require('plugins')
require('file-explorer')
require('mason-config')
require('gopls')
require('lsp-settings')
require('code-completion')
require('custom-keys')
require('styling')
require('file-finder')
require('syntax-highlight')
require('statusbar')
require('autobrackets')
--require('pageheader')
require('hoverdoc')
require('ident-guide')
require('telescopecfg')
--require "languages.css"
--require "languages.js-ts"